### ISSUE TITLE
Problems when connecting to a host by IP address instead of hostname

### ISSUE THREAD

**Issue by tsemczyszyn** [sangoma/safepy2#1]
When I try to connect with an IP address instead of a hostname it fails because we use the hostname to create  a python type, so numbers aren't allowed.

x = safe.api('10.10.10.10')
ValueError: Type names and field names cannot start with a number: '10'

Maybe we should look at providing a default typename for cases like this?

EDIT: IPv6 cases should be considered as well.

**Comment by vodik** [comment]
Ah shit. I use the host field to generate a typename for the `x` variable. That's why its breaking with IPs and its wrong in general:

``` python
    typename = make_typename(host.partition('.')[0].capitalize())
    namespace = compile_objects(ast, ub)
```
